### ISSUE TITLE
Principled Volume makes the addon not working

### ISSUE THREAD

**Issue by TarouMaso** [atticus-lv/LightLinkingPanel#5]
As soon we plug only a Principled Volume in the Volume input of the Material Output node the whole interface globally collapses:
![image](https://github.com/user-attachments/assets/4d041b19-066a-446d-8a3c-c91a454f3881)

With a Principled Volume plugged anywhere in the scene to any object the whole interface vanishes:
![image](https://github.com/user-attachments/assets/3484fbbe-1263-490f-a857-e71d6f2c467a)

It only shows again when you have a principled volume + anything in the surface plugged:
![image](https://github.com/user-attachments/assets/88aaf41d-ef59-411a-8789-56dc97139f46)

**Comment by xmx-emm** [comment]
This bug has been fixed
[v0.3.7](https://github.com/AIGODLIKE/LightHelper/releases/tag/v0.3.7)
